# Generated by Django 3.1 on 2020-10-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('edition', models.IntegerField(default=1)),
                ('publication_year', models.DateField()),
            ],
        ),
    ]
